Error building vignettes
Attempting to build sigfit on R 4.0.2 results in an error in vignette building. (error follows)
Trying suggestions in stack overflow post https://stackoverflow.com/a/66245782
Error: Failed to install 'sigfit' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in engine$weave(file, quiet = quiet, encoding = enc) :
E>   Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
E> Error: processing vignette 'sigfit_vignette.Rmd' failed with diagnostics:
E> The 'markdown' package should be declared as a dependency of the 'sigfit' package (e.g., in the  'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
E> --- failed re-building ‘sigfit_vignette.Rmd’
E>
E> SUMMARY: processing the following file failed:
E>   ‘sigfit_vignette.Rmd’
E>
E> Error: Vignette re-building failed